### ISSUE TITLE
can the same ray be picked more than once in the same iteration?

### ISSUE THREAD

**Issue by malfonsoarquimea** [facebookresearch/Neural_3D_Video#17]
When doing the sampling process for a given iteration, do you sample rays (according to the weights) with or without repetition?
Can the same ray appear more than once in the same iteration?
Thanks in advance!

**Comment by zhaoyang-lv** [comment]
The rays are sampled according to weights. It is possible they get more than one sample per iteration.

**Comment by malfonsoarquimea** [comment]
Thanks very much!
