### ISSUE TITLE
Training cameras

### ISSUE THREAD

**Issue by Caoang327** [facebookresearch/Neural_3D_Video#18]
Hi,

I wonder which cameras are you used in the paper for training? Specifically, there are 17 training cameras in the paper, but I found there are 21 cameras in flame salmon and many other scenes. May I know specifically which cameras are you using for training? Thanks

**Comment by zhaoyang-lv** [comment]
as said in the data note: 

* We have already filtered out the camera stream that is either unsynchronized, or have significant inconsistency in observations. If a camera stream ID does not exist in the folder, this is the invalid camera stream that has been filtered. This is why the number of cameras might vary in the released folder. 

* For all the dataset, cam00.mp4 is the center reference camera which we held out for testing. Training cameras are all others except this held out test view. The flame salmon scene is 18 camera which we used extensively for quantitative evaluation in the paper.
