### ISSUE TITLE
A question about video camera parameters. 

### ISSUE THREAD

**Issue by ellzeycunha0** [facebookresearch/Neural_3D_Video#24]
Hi. Thanks for your great work.
As you mentioned， each 6-DoF cam parameters is calculated by LLFF code in "pose_bounds.py". However, I only find the way to  calculate cam parameters with one or few static image/frame, not with videos. So, how to calculate one cam's parameters with many dynamic images in videos?

**Comment by zhaoyang-lv** [comment]
The poses are calculated based on one timestamp frames across all synchronized views.

**Comment by ellzeycunha0** [comment]
Thanks for your reply. There are 300 frames in a view. And you only use one timestamp frame for a view ?

**Comment by zhaoyang-lv** [comment]
That's right

**Comment by ellzeycunha0** [comment]
Thanks !
