### ISSUE TITLE
What does poses_bounds.npy excactly store?

### ISSUE THREAD

**Issue by oximi123** [facebookresearch/Neural_3D_Video#6]
Hey guys, I'am a little confused about the **poses_bounds.npy** file. I invesitaged the **coffee_martini** dataset and found a 18x17 matrix in **poses_bounds.npy**. I gues "18" refers to the number of video streams, but what does each row store? Which column is the tranformation matrix and which is the camera intrinsics?

**Comment by zhaoyang-lv** [comment]
The format is the same as the format pose used in original nerf dataset and local light field fusion dataset, explained at:
https://github.com/bmild/nerf#already-have-poses

18 refers to the number of video streams.
