### ISSUE TITLE
Data assets for outdoor scene

### ISSUE THREAD

**Issue by subin-kim-cv** [facebookresearch/Neural_3D_Video#7]
Hello, thanks for your great work and release of 3D video datasets.

I think some outdoor scene videos which are presented in the paper (https://arxiv.org/abs/2103.02597) were missing in the release Github pages. What I could find were only 6 videos of indoor scenes where the man is standalone and cooking some stuff.

Could you notify me where can I find these outdoor videos?
Also, if it is not been released yet, I want to know the plans for releasing the outdoor scenes.

I would be really grateful and these synchronized outdoor videos will encourage further future works related to synthesizing and rendering 3d videos.  

Thanks :)

**Comment by zhaoyang-lv** [comment]
Thanks for letting us know about it. We did not go through the release review for the outdoor videos. If you think it's helpful, we can put it as one todo. But that will require some internal review time to go through logistics, please be patient with that.

**Comment by Linyou** [comment]
> Thanks for letting us know about it. We did not go through the release review for the outdoor videos. If you think it's helpful, we can put it as one todo. But that will require some internal review time to go through logistics, please be patient with that.

Any plans to release the outdoor videos?
