### ISSUE TITLE
How to precompute all rays?

### ISSUE THREAD

**Issue by doramasma** [facebookresearch/Neural_3D_Video#8]
Hello, thanks for your great work and release of 3D video datasets.

Recently, I have been trying to do something similar to what is done in DyNeRF. However, my biggest problem, is that due to the number of frames there are, it is necessary, to calculate a lot of rays. Therefore, it is practically impossible to precompute all the rays, so I have to generate them in batches. However, the latter is quite inefficient. 

Can you give me more details on how to make the dataloader? 

Thanks :)

**Comment by zhaoyang-lv** [comment]
It is a very practical engineering problem. 

In the dataloader, here are the rough steps it need to do: 
* shuffle all the indices in the rays, and put all indices in a queue
* in each iteration, sample a number of ray indices according to the index queue, and load all relevant information. 

Depending on the system, the per-iteration ray loading might take sometime. It was particularly problematic for us using internal system that data reading bandwidth was limited. What we did to work around is to have one data loader loading all the cached rays in the backend using one/multiple threads.

**Comment by doramasma** [comment]
Hello,

Thank you very much for your quick response.

So, we pre-computed the rays prior to training (makes sense to me), what storage format are you using? To the best of my knowledge, the hdf5 format is normally used.  One of my concerns is that due to not having the rays in ram memory, the training speed of my algorithm will be affected. Any suggestions?

Thank you in advance

**Comment by zhaoyang-lv** [comment]
It is also tailored to the format that best suited for your system. hdf5 is good. You don't need to load the entire file into memory. Instead you need a caching thread to pre-load part of the database into the memory according to your sampling indices. Our internal system is different the the mechanism is the same.

**Comment by doramasma** [comment]
Thank you very much for your help!
